config/routes.rb
Jeddit::Application.routes.draw do

  get "posts/index"

  get "comments/create"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  resources :users, only: [:show]
  resources :posts, only: [:index]
  resources :users, only: [:show, :index]
  
  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts' do
      resources :comments, only: [:create, :destroy]
      resources :favorites, only: [:create, :destroy]
      match '/up-vote', to: 'votes#up_vote', as: :up_vote
      match '/down-vote', to: 'votes#down_vote', as: :down_vote
    end
  end

  match "about" => 'welcome#about', via: :get

  root :to => 'welcome#index'
end

app/views/layouts/_avatar.html.erb
<div class="border">
	<%= image_tag(current_user.avatar.url, class: "avatar") if current_user.avatar? %>
</div>

app/views/layouts/_footer.html.erb
<footer>
	<small>
		<div class="footerleft">Geddit&trade; 2013</div>
	</small>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <% if current_user %>
        <li><%= link_to "Topics", topics_path %></li>
        <li><%= link_to "Popular", posts_path %></li>
        <li><%= link_to "Users", users_path %></li>
      <% else %>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Popular", posts_path %></li>
        <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <p class="navbar-text">
        <span class="bumpright">
        <% if current_user %>
<!--       <div class="navatar">
            <%= render partial: 'layouts/avatar' %>
          </div>  -->
         Hello <%= link_to (current_user.name || current_user.email), current_user %>!
           <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or 
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </span>
      </p>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geddit</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'layouts/nav' %>
  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <%= yield %>
    <%= render partial: 'layouts/footer' %>
  </div>
<%= javascript_include_tag "application" %>
</body>
</html>